spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: *****
    password: *****
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
        ddl-auto: update
